//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActivity
    {
        public int CategoryID { get; set; }
        public string actName { get; set; }
        public string actProvider { get; set; }
        public int actNumber { get; set; }
        public string actPrice { get; set; }
        public string actWebsite { get; set; }
        public string actLocationData { get; set; }
        public string actImgFile { get; set; }
        public string Adress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
    }
}
